# Generated by Django 2.2 on 2019-04-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skiresorts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='skiresort',
            table='skiresorts',
        ),
    ]
