# Generated by Django 2.2 on 2019-04-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiresorts', '0002_auto_20190420_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='skiresort',
            name='enabled',
            field=models.NullBooleanField(),
        ),
    ]
