# Generated by Django 2.2 on 2019-04-25 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skiresorts', '0002_auto_20190420_2134'),
        ('slopes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slope',
            name='aerialway',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slope',
            name='fk_skiresort',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='slope',
            name='highway',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slope',
            name='other_tags',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='slope',
            name='skiresort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skiresorts.Skiresort'),
        ),
        migrations.AlterField(
            model_name='slope',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
