# Generated by Django 2.2 on 2019-04-25 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slopes', '0002_auto_20190425_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slope',
            name='fk_skiresort',
        ),
        migrations.AlterField(
            model_name='slope',
            name='skiresort',
            field=models.ForeignKey(db_column='fk_skiresort', null=True, on_delete=django.db.models.deletion.CASCADE, to='skiresorts.Skiresort'),
        ),
    ]
