# Generated by Django 2.2 on 2019-04-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slopes', '0003_auto_20190425_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='slope',
            name='status',
            field=models.NullBooleanField(),
        ),
    ]
