# Generated by Django 2.2 on 2019-04-28 13:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slopes', '0004_slope_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slope',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
