# Generated by Django 2.2 on 2019-04-28 13:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slopes', '0005_auto_20190428_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slope',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=21781),
        ),
    ]
