# Generated by Django 2.2 on 2019-04-28 13:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slopes', '0007_auto_20190428_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slope',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326),
        ),
    ]
